// <auto-generated />
namespace cm.backend.domain.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialtest));
        
        string IMigrationMetadata.Id
        {
            get { return "201610072148578_initial-test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
